# Generated by Django 5.0 on 2023-12-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_address', models.TextField()),
                ('user_photo', models.FileField(upload_to='Userdocs/')),
                ('user_proof', models.FileField(upload_to='Userdocs/')),
                ('user_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.tbl_place')),
            ],
        ),
    ]
