# Generated by Django 5.0 on 2024-01-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_subcategory'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminregistration',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
